# Minecraft Server Properties - Tuning de Rede & Performance
server-port=25565
server-ip=0.0.0.0
network-compression-threshold=256
prevent-proxy-connections=false
online-mode=true
enforce-secure-profile=false

# Limites e Otimização de Ticks
view-distance=8
simulation-distance=6
sync-chunk-writes=false
enable-status=true
max-players=100
motd=\u00a7bPaperMC \u00a78|\u00a7f Crossplay Bedrock & Java \u00a7a[20 TPS]
